# This Plugin Is Created By @StarkxD

from telethon import events
import random
import re
from userbot.utils import admin_cmd
import asyncio


@borg.on(admin_cmd("fban ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    FBAN = event.pattern_match.group(1)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ENTER FED ID WHERE YOU ARE ADMIN")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(100)
